apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: gutenshare-backend
  name: gutenshare-backend
spec:
  ports:
  - name: "28080"
    port: 28080
    targetPort: 8080
  selector:
    io.kompose.service: gutenshare-backend
status:
  loadBalancer: {}
